### ISSUE TITLE
Updating to OS 6 may break the integration.

### ISSUE THREAD

**Issue by bengAThome** [davewatson91/hass-amber-electric#7]
So I upgraded to Home Assistant 6.0 today, and of course the "old" amberelectric integration broke.
I used file editor to rename the old custom components folder, and uploaded this repository to a "new" custom_components/amberelectric folder.
Then reloaded core from the file editor integration.
No errors there, but also no sensors.

So I went to Supervisor and asked it to reload the core there.
This produced the error:
The system cannot restart because the configuration is not valid: Platform error sensor.amberelectric - Integration 'amberelectric' not found.

So I'm at a loss to whats wrong.
Checked folder names etc are correct. Even deleted the "oldamberelectric" directory from the shell (___py___ files are hidden...)

I thought this would be an easy fix...but not so. 
I'll rollback the snapshot and try upgrading with this manifest version first before updating to OS6.0.

**Comment by bengAThome** [comment]
Hmm...
Ok. This time all I did was replace the old manifest file, with this one here, and attempting to restart core fails with the same error....

**Comment by bengAThome** [comment]
Wait...even though I rolled back to an older snapshot...HA still says 6.0....Not sure whats going on there....

**Comment by davewatson91** [comment]
Definitely something funky going on - I'm not running supervised, so can't help with that aspect, but I'm on Home Assistant 2021.6.2 without an issue at all.....

**Comment by bengAThome** [comment]
Well, its got me stumped. Rolback is not working at all. 
But, one thing i noticed, doesn't the manifest file need a version?
eg:
"version": "1.0",

**Comment by davewatson91** [comment]
[It has one? ](https://github.com/davewatson91/hass-amber-electric/blob/master/custom_components/amberelectric/manifest.json)

**Comment by bengAThome** [comment]
Argh...ok. Not sure what is going on....
Somehow the snapshot rollback, rolled the manifest back, but not the OS, makes me wonder what a "full snapshot" is.
Anyway...editing the manifest file with the code here..which DOES include a version...sorry Dave.....and saving it seems to have worked.
So I'll close this issue and only assume it was some kind of operator error.... :/facepalm:/
